from setuptools import setup, find_packages

setup(
    name="p3if",
    version="1.0.0",
    packages=find_packages(include=['p3if_*', 'utils', 'data']),
    install_requires=[
        "pandas>=2.2.2",
        "numpy>=1.26.0",
        "scipy>=1.11.0",
        "scikit-learn>=1.3.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.13.0",
        "plotly>=5.14.0",
        "flask>=2.3.0",
        "flask-cors>=4.0.0",
        "jinja2>=3.1.0",
        "beautifulsoup4>=4.9.0",
        "markdown>=3.3.0",
        "pydantic>=2.0.0",
        "networkx>=3.0",
        "pytest>=8.0.0",
        "pytest-asyncio>=0.21.0",
        "tqdm>=4.65.0",
        "pyyaml>=6.0.0",
        "csscompressor>=0.9.5",
        "jsmin>=3.0.1",
        "Pillow>=10.0.0"
    ],
    python_requires=">=3.8",
    description="Property-Process-Perspective Integration Framework",
    author="P3IF Team",
    long_description="A sophisticated framework for integrating and visualizing complex data relationships across multiple domains through patterns (properties), processes, and perspectives.",
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Scientific/Engineering",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Distributed Computing",
    ],
) 